# Generated by Django 4.0.3 on 2023-08-01 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        ('brand', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadSource',
            fields=[
                ('LeadSourceID', models.AutoField(primary_key=True, serialize=False)),
                ('LeadSource', models.CharField(choices=[('Incoming', 'Incoming'), ('Facebook', 'Facebook'), ('Google', 'Google')], max_length=50)),
                ('Status', models.CharField(default='Active', max_length=20)),
                ('DisplayStatus', models.BooleanField(default=True)),
                ('Brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brand.brand')),
                ('Company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
        ),
    ]
