# Generated by Django 4.0.3 on 2023-08-18 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadfollowup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadfollowup',
            name='LeadStatus',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
