# Generated by Django 4.0.3 on 2023-08-18 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadfollowup', '0002_alter_leadfollowup_leadstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadfollowup',
            name='LeadPhonePicked',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='leadfollowup',
            name='LeadStatus',
            field=models.CharField(choices=[('Followup', 'Followup'), ('Visit scheduled', 'Visit scheduled'), ('Demo scheduled', 'Demo scheduled'), ('Call Later', 'Call Later'), ('Not Intersted', 'Not Intersted')], max_length=2000, null=True),
        ),
    ]
