# Generated by Django 4.0.3 on 2023-09-01 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadfollowup', '0007_leadfollowup_leadrepname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadfollowup',
            name='leadRepName',
            field=models.CharField(max_length=200),
        ),
    ]
