# Generated by Django 4.0.3 on 2023-10-28 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_alter_service_servicemode'),
        ('leadfollowup', '0010_leadfollowup_leadserviceinterested'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leadfollowup',
            name='LeadServiceInterested',
        ),
        migrations.AddField(
            model_name='leadfollowup',
            name='LeadServiceInterested',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='service.service'),
        ),
    ]
