# Generated by Django 4.0.3 on 2023-10-29 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leadfollowup', '0011_remove_leadfollowup_leadserviceinterested_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leadfollowup',
            name='leadRepName',
        ),
    ]
