# Generated by Django 4.0.3 on 2023-10-30 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_alter_service_servicemode'),
        ('leadfollowup', '0012_remove_leadfollowup_leadrepname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadfollowup',
            name='LeadServiceInterested',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.service'),
        ),
    ]
