# Generated by Django 4.0.3 on 2023-11-26 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadfollowup', '0017_alter_leadfollowup_leadcomments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadfollowup',
            name='LeadComments',
            field=models.TextField(null=True),
        ),
    ]
