# Generated by Django 4.0.3 on 2023-10-18 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_alter_service_servicemode'),
        ('leadlastfollowup', '0005_alter_leadlastfollowup_leadstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadlastfollowup',
            name='LeadServiceInterested',
            field=models.ManyToManyField(to='service.service'),
        ),
    ]
