# Generated by Django 4.0.3 on 2023-11-26 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadlastfollowup', '0012_alter_leadlastfollowup_leadcomments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadlastfollowup',
            name='LeadComments',
            field=models.TextField(null=True),
        ),
    ]
