# Generated by Django 4.0.3 on 2023-08-18 05:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0001_initial'),
        ('lead', '0001_initial'),
        ('brand', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadFollowUp',
            fields=[
                ('LeadFollowupID', models.AutoField(primary_key=True, serialize=False)),
                ('LeadFollowupCreatedDate', models.DateTimeField(auto_now_add=True)),
                ('LeadPhonePicked', models.BooleanField(null=True)),
                ('LeadStatus', models.CharField(max_length=2000)),
                ('LeadStatusDate', models.DateTimeField(blank=True, null=True)),
                ('LeadEvent', models.CharField(blank=True, choices=[('Visit happened', 'Visit happened'), ('Demo happened', 'Demo happened')], max_length=20, null=True)),
                ('LeadEventDate', models.DateTimeField(blank=True, null=True)),
                ('LeadEventTakenBy', models.CharField(max_length=100)),
                ('LeadFeeOffered', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('LeadReasonPhoneNotPicked', models.TextField(blank=True, null=True)),
                ('Brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brand.brand')),
                ('Company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
                ('LeadID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lead.lead')),
                ('LeadRep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
