# Generated by Django 4.0.3 on 2023-08-21 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadfollowup', '0004_alter_leadfollowup_leadstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadfollowup',
            name='LeadStatus',
            field=models.CharField(choices=[('Ready To Enroll', 'Ready To Enroll'), ('Visit scheduled', 'Visit scheduled'), ('Demo scheduled', 'Demo scheduled'), ('Highly Intersted', 'Highly Intersted'), ('Least Intersted', 'Least Intersted'), ('Not Intersted', 'Not Intersted')], max_length=2000, null=True),
        ),
    ]
