# Generated by Django 4.0.3 on 2023-08-25 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        ('brand', '0001_initial'),
        ('lead', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_confirmation_id', models.CharField(max_length=50)),
                ('customer_id', models.CharField(blank=True, max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('payment_date', models.DateTimeField()),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_currency', models.CharField(max_length=10)),
                ('payment_purpose_name', models.CharField(max_length=200)),
                ('payment_mode', models.CharField(max_length=100)),
                ('payment_status', models.CharField(default='Approved', max_length=20)),
                ('payment_current_status', models.CharField(default='Active', max_length=20)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brand.brand')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
                ('lead_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lead.lead')),
            ],
        ),
    ]
