# Generated by Django 4.0.3 on 2023-08-25 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paymenttype', '0001_initial'),
        ('payment', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_type_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='paymenttype.paymenttype'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(max_length=1000),
        ),
    ]
