# Generated by Django 4.0.3 on 2023-11-14 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_alter_payment_payment_type_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='payment_mode',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_purpose_name',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_type',
        ),
    ]
