# Generated by Django 4.0.3 on 2023-09-20 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payment', '0005_alter_payment_payment_type_id'),
        ('customerstudent', '0004_customer_customerdob_customer_customergender_and_more'),
        ('paymentmode', '0001_initial'),
        ('lead', '0005_alter_lead_coursename'),
        ('company', '0001_initial'),
        ('convertedstudent', '0003_alter_convertedstudent_nextduedate'),
        ('paymenttype', '0001_initial'),
        ('brand', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeRefund',
            fields=[
                ('FeeID', models.AutoField(primary_key=True, serialize=False)),
                ('FeeRefunded', models.DecimalField(decimal_places=2, max_digits=10)),
                ('FeeRefundedCreatedDateTime', models.DateTimeField()),
                ('FeeRefundedDateTime', models.DateTimeField()),
                ('ReceiptNumber', models.CharField(max_length=20)),
                ('UpdatedBY', models.CharField(max_length=400)),
                ('Representative', models.CharField(max_length=200)),
                ('CustomerStatus', models.CharField(default='Active', max_length=20)),
                ('Brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brand.brand')),
                ('Company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
                ('ConvertedID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='convertedstudent.convertedstudent')),
                ('LeadID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lead.lead')),
                ('PaymentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.payment')),
                ('PaymentMode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paymentmode.paymentmode')),
                ('PaymentType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paymenttype.paymenttype')),
                ('StudentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customerstudent.customer')),
            ],
        ),
    ]
