# Generated by Django 4.0.3 on 2023-09-20 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refundfees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feerefund',
            name='ReceiptNumber',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
