# Generated by Django 4.0.3 on 2023-12-14 10:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('refundfees', '0004_rename_feeid_feerefund_feerefundid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feerefund',
            name='Representative',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
