# Generated by Django 4.0.3 on 2024-01-12 08:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('refundfees', '0006_alter_feerefund_representative'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feerefund',
            name='FeeRefundedCreatedDateTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='feerefund',
            name='FeeRefundedDateTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
