# Generated by Django 4.0.3 on 2023-08-18 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadlastfollowup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadlastfollowup',
            name='LeadStatus',
            field=models.CharField(choices=[('Followup', 'Followup'), ('Visit scheduled', 'Visit scheduled'), ('Demo scheduled', 'Demo scheduled'), ('Call Later', 'Call Later'), ('Not Intersted', 'Not Intersted')], max_length=2000, null=True),
        ),
    ]
