# Generated by Django 4.0.3 on 2023-10-26 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('messagetemplate', '0001_initial'),
        ('lead', '0007_remove_lead_leadserviceinterested_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageLog',
            fields=[
                ('LogID', models.AutoField(primary_key=True, serialize=False)),
                ('Date', models.DateField()),
                ('Attachment', models.FileField(null=True, upload_to='attachments/')),
                ('CompanyID', models.ManyToManyField(to='lead.lead')),
                ('TemplateID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messagetemplate.smstemplate')),
            ],
        ),
    ]
