# Generated by Django 4.0.3 on 2023-11-29 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('brand', '0001_initial'),
        ('lead', '0012_alter_lead_leadstatus'),
        ('messagelog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagelog',
            name='Attachment',
        ),
        migrations.AddField(
            model_name='messagelog',
            name='BrandId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='brand.brand'),
        ),
        migrations.AddField(
            model_name='messagelog',
            name='LeadId',
            field=models.ForeignKey(default=107, on_delete=django.db.models.deletion.CASCADE, to='lead.lead'),
        ),
        migrations.RemoveField(
            model_name='messagelog',
            name='CompanyID',
        ),
        migrations.AddField(
            model_name='messagelog',
            name='CompanyID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='company.company'),
        ),
        migrations.AlterField(
            model_name='messagelog',
            name='Date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
