# Generated by Django 4.0.3 on 2023-11-29 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('brand', '0001_initial'),
        ('lead', '0012_alter_lead_leadstatus'),
        ('messagelog', '0002_remove_messagelog_attachment_messagelog_brandid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagelog',
            name='BrandId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brand.brand'),
        ),
        migrations.AlterField(
            model_name='messagelog',
            name='CompanyID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company'),
        ),
        migrations.AlterField(
            model_name='messagelog',
            name='LeadId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lead.lead'),
        ),
    ]
