# Generated by Django 4.0.3 on 2023-12-12 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messagelog', '0003_alter_messagelog_brandid_alter_messagelog_companyid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagelog',
            name='MessageBody',
            field=models.TextField(default='Hello, Sakshi Tiwari your Payment has been done Rs. 5000'),
        ),
    ]
