# Generated by Django 4.0.3 on 2023-09-27 08:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('BatchID', models.AutoField(primary_key=True, serialize=False)),
                ('BatchName', models.CharField(max_length=255)),
                ('BatchDescription', models.TextField()),
                ('BatchMode', models.CharField(choices=[('Offline', 'Offline'), ('Online', 'Online')], max_length=10)),
                ('BatchTags', models.CharField(choices=[('MWF', 'MWF'), ('TTS', 'TTS'), ('Weekdays', 'Weekdays'), ('Weekends', 'Weekends')], max_length=20)),
                ('BatchCreatedDate', models.DateTimeField(auto_now_add=True)),
                ('BatchStartDate', models.DateTimeField()),
                ('BatchEndDate', models.DateTimeField()),
                ('BatchTime', models.TimeField()),
                ('BatchEndTime', models.TimeField()),
                ('Status', models.BooleanField(default=True)),
                ('BatchTeacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
