# Generated by Django 4.0.3 on 2023-09-29 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='BatchStaffAssigned',
            field=models.CharField(default='Staff 1', max_length=300),
        ),
        migrations.AddField(
            model_name='batch',
            name='BatchTeacherName',
            field=models.CharField(default='Teacher 1', max_length=200),
        ),
    ]
