# Generated by Django 4.0.3 on 2023-10-03 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0002_batch_batchstaffassigned_batch_batchteachername'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='BatchStaffAssigned',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='batch',
            name='BatchTeacherName',
            field=models.CharField(max_length=200),
        ),
    ]
