# Generated by Django 4.0.3 on 2024-01-15 17:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0003_alter_batch_batchstaffassigned_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='BatchCreatedDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
