# Generated by Django 4.0.3 on 2023-08-01 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BrandShortCode', models.CharField(max_length=10)),
                ('BrandName', models.CharField(max_length=100)),
                ('BrandAddress', models.TextField()),
                ('BrandPhone', models.CharField(max_length=20)),
                ('BrandEmail', models.EmailField(max_length=254)),
                ('BrandLocation', models.CharField(max_length=100)),
                ('BrandWebsite', models.URLField(blank=True, null=True)),
                ('BrandNewLeadAddAPI', models.URLField(blank=True, null=True)),
                ('BrandSMSID', models.CharField(blank=True, max_length=100, null=True)),
                ('BrandSMSGateway', models.CharField(blank=True, max_length=100, null=True)),
                ('BrandSMSAPIKey', models.CharField(blank=True, max_length=100, null=True)),
                ('BrandEMailGateway', models.CharField(blank=True, max_length=100, null=True)),
                ('BrandEMailAPIKey', models.CharField(blank=True, max_length=100, null=True)),
                ('BrandEMailRegisteredID', models.CharField(blank=True, max_length=100, null=True)),
                ('BrandPaymentGatway', models.CharField(blank=True, max_length=100, null=True)),
                ('BrandPaymentGatwayAPIKey', models.CharField(blank=True, max_length=100, null=True)),
                ('BrandPaymentGatwayAuthToken', models.CharField(blank=True, max_length=100, null=True)),
                ('BrandPaymentGatwayRegisteredID', models.CharField(blank=True, max_length=100, null=True)),
                ('BrandPaymentGatwayRedirectURL', models.URLField(blank=True, null=True)),
                ('BrandPaymentGatwayWebhookURL', models.URLField(blank=True, null=True)),
                ('BrandThankYouURL', models.URLField(blank=True, null=True)),
                ('BrandFacebookPageID', models.CharField(blank=True, max_length=100, null=True)),
                ('BrandFacebookPageAccessToken', models.CharField(blank=True, max_length=200, null=True)),
                ('BrandWebDisplay', models.CharField(blank=True, max_length=100, null=True)),
                ('BrandRecaptchaSecret', models.CharField(blank=True, max_length=200, null=True)),
                ('BrandClassMode', models.CharField(blank=True, max_length=20, null=True)),
                ('Company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
        ),
    ]
