# Generated by Django 4.0.3 on 2023-08-30 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('convertedstudent', '0001_initial'),
        ('feetracer', '0002_alter_fee_fee_created_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fee',
            name='converted_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='converted_fees', to='convertedstudent.convertedstudent'),
        ),
    ]
