# Generated by Django 4.0.3 on 2023-08-08 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_alter_service_brand_alter_service_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='serviceMode',
            field=models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], default='offline', max_length=10),
        ),
    ]
