# Generated by Django 4.0.3 on 2023-08-11 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_alter_service_servicemode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='serviceMode',
            field=models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline')], max_length=10),
        ),
    ]
