# Generated by Django 4.0.3 on 2023-11-09 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0001_initial'),
        ('company', '0001_initial'),
        ('usercourse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercourse',
            name='BrandID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='brand.brand'),
        ),
        migrations.AddField(
            model_name='usercourse',
            name='CompanyID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='company.company'),
        ),
    ]
