<<<<<<< HEAD
# Generated by Django 4.0.3 on 2023-07-25 06:58

from django.db import migrations, models
=======
# Generated by Django 4.0.3 on 2023-08-04 08:41

from django.db import migrations, models
import django.db.models.deletion
>>>>>>> bbddb05 (Upadted Version 1.0)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
=======
        ('brand', '0001_initial'),
        ('company', '0001_initial'),
>>>>>>> bbddb05 (Upadted Version 1.0)
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.IntegerField()),
                ('status', models.CharField(max_length=255)),
                ('online_status', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=255)),
<<<<<<< HEAD
                ('company_id', models.CharField(max_length=255)),
                ('brand_allocated', models.CharField(max_length=255)),
=======
>>>>>>> bbddb05 (Upadted Version 1.0)
                ('user_location', models.CharField(max_length=255)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('user_create_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
<<<<<<< HEAD
=======
                ('brand', models.ManyToManyField(to='brand.brand')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
>>>>>>> bbddb05 (Upadted Version 1.0)
            ],
            options={
                'abstract': False,
            },
        ),
    ]
