# Generated by Django 4.0.3 on 2023-08-29 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lead', '0001_initial'),
        ('company', '0001_initial'),
        ('brand', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('CustomerID', models.AutoField(primary_key=True, serialize=False)),
                ('CustomerQRCode', models.CharField(blank=True, max_length=100, null=True)),
                ('Attendance', models.BooleanField(default=False)),
                ('CustomerName', models.CharField(max_length=200)),
                ('CustomerShippingAddress', models.TextField(blank=True, null=True)),
                ('CustomerBillingAddress', models.TextField(blank=True, null=True)),
                ('CustomerGST', models.CharField(blank=True, max_length=20, null=True)),
                ('CustomerLocation', models.CharField(blank=True, max_length=100, null=True)),
                ('CustomerPAN', models.CharField(blank=True, max_length=20, null=True)),
                ('CustomerPhone', models.CharField(max_length=20)),
                ('CustomerEmail', models.EmailField(max_length=254)),
                ('Brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brand.brand')),
                ('Company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
                ('LeadID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lead.lead')),
            ],
        ),
    ]
