# Generated by Django 4.0.3 on 2023-09-14 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerstudent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='CustomerPhoto',
            field=models.ImageField(null=True, upload_to='thumbNailImg'),
        ),
    ]
