# Generated by Django 4.0.3 on 2023-09-14 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerstudent', '0003_alter_customer_customerphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='CustomerDOB',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='CustomerGender',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='CustomerOccupation',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
