# Generated by Django 4.0.3 on 2023-09-02 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convertedstudent', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='convertedstudent',
            name='NextDue',
        ),
        migrations.AddField(
            model_name='convertedstudent',
            name='NextDueDate',
            field=models.DateField(default='2023-09-06'),
        ),
    ]
