# Generated by Django 4.0.3 on 2023-09-02 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convertedstudent', '0002_remove_convertedstudent_nextdue_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convertedstudent',
            name='NextDueDate',
            field=models.DateField(),
        ),
    ]
