# Generated by Django 4.0.3 on 2023-11-20 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_alter_service_servicemode'),
        ('convertedstudent', '0004_convertedstudent_courseid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convertedstudent',
            name='CourseID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.service'),
        ),
    ]
