# Generated by Django 4.0.3 on 2023-10-26 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SMSTemplate',
            fields=[
                ('TemplateID', models.AutoField(primary_key=True, serialize=False)),
                ('TemplateName', models.CharField(max_length=255)),
                ('TemplateMessage', models.TextField()),
                ('Status', models.CharField(choices=[('active', 'Active'), ('not_active', 'Not Active')], max_length=20)),
                ('CreatedDateTime', models.DateTimeField(auto_now_add=True)),
                ('LastUpdatedDateTime', models.DateTimeField(auto_now=True)),
                ('CCTO', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
