# Generated by Django 4.0.3 on 2023-11-29 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('brand', '0001_initial'),
        ('messagetemplate', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smstemplate',
            name='CCTO',
        ),
        migrations.AddField(
            model_name='smstemplate',
            name='Brand',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='brand.brand'),
        ),
        migrations.AddField(
            model_name='smstemplate',
            name='CompanyID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='company.company'),
        ),
        migrations.AddField(
            model_name='smstemplate',
            name='DLFID',
            field=models.PositiveBigIntegerField(default=1207161520341994378),
        ),
        migrations.AddField(
            model_name='smstemplate',
            name='SMSTemplateVariables',
            field=models.CharField(default='name', max_length=500),
        ),
    ]
