# Generated by Django 4.0.3 on 2023-11-29 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('brand', '0001_initial'),
        ('messagetemplate', '0002_remove_smstemplate_ccto_smstemplate_brand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smstemplate',
            name='Brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brand.brand'),
        ),
        migrations.AlterField(
            model_name='smstemplate',
            name='CompanyID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company'),
        ),
        migrations.AlterField(
            model_name='smstemplate',
            name='SMSTemplateVariables',
            field=models.CharField(max_length=500),
        ),
    ]
