# Generated by Django 4.0.3 on 2023-08-01 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        ('brand', '0001_initial'),
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LeadName', models.CharField(max_length=100)),
                ('LeadPhone', models.CharField(max_length=20)),
                ('LeadEmail', models.EmailField(max_length=254)),
                ('LeadLocation', models.CharField(max_length=100)),
                ('LeadAddress', models.CharField(max_length=200)),
                ('LeadSource', models.CharField(max_length=100)),
                ('Profession', models.CharField(max_length=200)),
                ('PageSource', models.CharField(max_length=100)),
                ('Plateform', models.CharField(max_length=100)),
                ('LeadDateTime', models.DateTimeField()),
                ('LeadStatus', models.CharField(max_length=50)),
                ('DND', models.BooleanField(default=False)),
                ('LeadRepresentativePrimary', models.CharField(max_length=100)),
                ('LeadRepresentativeSecondary', models.CharField(max_length=100)),
                ('LeadCountry', models.CharField(max_length=100)),
                ('LeadState', models.CharField(max_length=100)),
                ('LeadAssignmentAlgo', models.CharField(max_length=100)),
                ('LeadNextCallDate', models.DateField()),
                ('Brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brand.brand')),
                ('Company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
                ('LeadServiceInterested', models.ManyToManyField(to='service.service')),
            ],
        ),
    ]
