# Generated by Django 4.0.3 on 2023-09-02 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0003_alter_lead_leadserviceinterested'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='CourseName',
            field=models.CharField(default='Python', max_length=300),
        ),
    ]
