# Generated by Django 4.0.3 on 2023-10-18 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_alter_service_servicemode'),
        ('lead', '0006_alter_lead_leadstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='LeadServiceInterested',
        ),
        migrations.AddField(
            model_name='lead',
            name='LeadServiceInterested',
            field=models.ManyToManyField(to='service.service'),
        ),
    ]
