# Generated by Django 4.0.3 on 2023-10-27 09:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leadScource', '0001_initial'),
        ('lead', '0007_remove_lead_leadserviceinterested_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='LeadScourceId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='leadScource.leadsource'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='LeadRepresentativePrimary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='LeadRepresentativePrimary', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lead',
            name='LeadRepresentativeSecondary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='LeadRepresentativeSecondary', to=settings.AUTH_USER_MODEL),
        ),
    ]
