# Generated by Django 4.0.3 on 2023-10-28 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leadScource', '0001_initial'),
        ('lead', '0008_lead_leadscourceid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='LeadScourceId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leadScource.leadsource'),
        ),
    ]
