# Generated by Django 4.0.3 on 2023-10-30 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0009_alter_lead_leadscourceid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='CourseName',
        ),
    ]
