# Generated by Django 4.0.3 on 2023-09-22 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Package', models.CharField(max_length=255)),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('RepID', models.IntegerField()),
                ('RepName', models.CharField(max_length=255)),
                ('PaymentLink', models.URLField()),
                ('PaymentAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('PaymentLinkCreatedDateTime', models.DateTimeField(auto_now_add=True)),
                ('PaymentLinkExpiryDateTime', models.DateTimeField(blank=True, null=True)),
                ('Status', models.CharField(default='Active', max_length=50)),
            ],
        ),
    ]
