# Generated by Django 4.0.3 on 2023-09-22 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paymentlink', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Payment',
            new_name='PaymentLink',
        ),
    ]
