# Generated by Django 4.0.3 on 2023-09-25 05:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import paymentlink.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('paymentlink', '0002_rename_payment_paymentlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentlink',
            name='PaymentLink',
            field=models.URLField(default=paymentlink.models.generate_unique_url, unique=True),
        ),
        migrations.AlterField(
            model_name='paymentlink',
            name='RepID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
