# Generated by Django 4.0.3 on 2023-08-25 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paymenttype', '0001_initial'),
        ('payment', '0004_payment_payment_type_id_alter_payment_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paymenttype.paymenttype'),
        ),
    ]
