# Generated by Django 4.0.3 on 2023-10-26 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emaillog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emaillog',
            old_name='TemplateID',
            new_name='template_id',
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='Date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
