# Generated by Django 4.0.3 on 2023-09-18 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('MenuItemDescription', models.CharField(max_length=255)),
                ('MenuType', models.CharField(choices=[('div', 'div'), ('ul', 'ul'), ('li', 'li')], max_length=10)),
                ('MenuLink', models.URLField()),
                ('PageTitle', models.CharField(max_length=255)),
                ('BrandIDArray', models.CharField(max_length=255)),
                ('Level', models.PositiveIntegerField()),
                ('MenuIdentifier', models.CharField(max_length=255)),
                ('UserRoles', models.CharField(max_length=255)),
                ('DisplayOrder', models.PositiveIntegerField()),
                ('ActiveStatus', models.CharField(choices=[('Active', 'Active'), ('NonActive', 'NonActive')], max_length=10)),
                ('ArchiveStatus', models.CharField(choices=[('Deleted', 'Deleted')], max_length=10)),
                ('AccessLevel', models.PositiveIntegerField(choices=[(10, '10'), (20, '20'), (30, '30'), (100, '100')])),
                ('CreateUpto', models.PositiveIntegerField(choices=[(10, '10'), (20, '20'), (30, '30'), (100, '100')])),
                ('UpdateUpto', models.PositiveIntegerField(choices=[(10, '10'), (20, '20'), (30, '30'), (100, '100')])),
                ('DeleteUpto', models.PositiveIntegerField(choices=[(10, '10'), (20, '20'), (30, '30'), (100, '100')])),
                ('ParentID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='navbar.menuitem')),
            ],
        ),
    ]
