# Generated by Django 4.0.3 on 2023-09-18 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navbar', '0003_alter_menuitem_menuidentifier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='DisplayOrder',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
