# Generated by Django 4.0.3 on 2023-11-05 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navbar', '0004_alter_menuitem_displayorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='EndPoint',
            field=models.CharField(default='dashboard', max_length=20),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='MenuLink',
            field=models.URLField(default='http://localhost:5173'),
        ),
    ]
