# Generated by Django 4.0.3 on 2023-11-05 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navbar', '0005_menuitem_endpoint_alter_menuitem_menulink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='EndPoint',
            field=models.CharField(max_length=20),
        ),
    ]
