# Generated by Django 4.0.3 on 2023-08-18 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Country', models.CharField(max_length=100)),
                ('StateName', models.CharField(max_length=100)),
                ('StateCode', models.CharField(max_length=10)),
                ('Active', models.BooleanField(default=True)),
            ],
        ),
    ]
